apiVersion: v1
kind: Template
metadata:
  name: archivist

parameters:

- name: NAME
  description: The name of the DeploymentConfig.
  value: "archivist"
- name: GIT_REPO
  description: Git repository housing the Archivist Dockerfile and application code to build and deploy.
  value: "git@github.com:openshift/online-archivist.git"
- name: GIT_REF
  description: Git branch, commit, or tag to deploy.
  value: "master"
- name: GIT_SSH_KEY
  description: A base64 encoded GitHub deployer ssh key for the online repo.
  required: true
- name: LOG_LEVEL
  value: info
- name: NAMESPACE_HIGH_WATERMARK
  required: true
- name: NAMESPACE_LOW_WATERMARK
  required: true
- name: MIN_INACTIVE_DAYS
  required: true
- name: MAX_INACTIVE_DAYS
  required: true

objects:

- apiVersion: v1
  kind: ClusterRole
  metadata:
    annotations:
      authorization.openshift.io/system-only: "true"
    name: ${NAME}
  rules:
  - resources:
    - projects
    - namespaces
    - replicationcontrollers
    - builds
    - buildconfigs
    verbs:
    - watch
    - get
    - list
    - create
    - update
    - delete

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${NAME}

- apiVersion: v1
  kind: ClusterRoleBinding
  metadata:
    name: ${NAME}
  roleRef:
    name: ${NAME}
  subjects:
  - kind: ServiceAccount
    name: ${NAME}
    namespace: openshift-infra

- kind: Secret
  apiVersion: v1
  data:
    ssh-privatekey: ${GIT_SSH_KEY}
  kind: Secret
  metadata:
    name: ${NAME}-sshkey
  type: kubernetes.io/ssh-auth

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
  status:
    dockerImageRepository:

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_REF}
      sourceSecret:
        name: ${NAME}-sshkey
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: golang:1.7
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    triggers:
      - type: ConfigChange

- kind: "ConfigMap"
  apiVersion: v1
  metadata:
    name: ${NAME}
  data:
    archivist.cfg: |
      logLevel: ${LOG_LEVEL}
      clusters:
      - name: CLUSTERNAME
        namespaceCapacity:
          highWatermark: ${NAMESPACE_HIGH_WATERMARK}
          lowWatermark: ${NAMESPACE_LOW_WATERMARK}
        minInactiveDays: ${MIN_INACTIVE_DAYS}
        maxInactiveDays: ${MAX_INACTIVE_DAYS}
      protectedNamespaces:
      - openshift-infra
      - default
      - openshift
      - kube-system
      - logging

- kind: "DeploymentConfig"
  apiVersion: v1
  metadata:
    name: ${NAME}
  spec:
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${NAME}
          from:
            kind: ImageStreamTag
            name: ${NAME}:latest
    replicas: 1
    selector:
      name: ${NAME}
    template:
      metadata:
        labels:
          name: ${NAME}
      spec:
        serviceAccountName: ${NAME}
        containers:
          - name: ${NAME}
            # References our image stream above:
            image: online-archivist
            volumeMounts:
              - name: config-volume
                mountPath: /etc/archivist/
            command: [ "archivist","monitor","--config","/etc/archivist/archivist.cfg" ]
        volumes:
          - name: config-volume
            configMap:
              name: ${NAME}
